link to specific modules used in rtlib
viscenter/registration-toolkit pull request #25
Opened 2019-04-16 12:53 UTC by stephenrparsons

This got me around some undefined reference errors when linking. I did this instead of ${VTK_LIBRARIES} to avoid bringing in all VTK libraries and their associated dependencies, since that could bring Qt or similar into the mix when that is not necessary.

2019-04-16 13:43 UTC, csparker247 commented on rtlib/CMakeLists.txt
> +	vtkFiltersGeneral
If things are included in headers, they should be added to PUBLIC linkage. If in a cpp, to PRIVATE linkage. This looks like the minimal set of VTK libraries for `rtlib`:
```cmake
PUBLIC
    vtkCommonCore
    vtkCommonDataModel
PRIVATE
    vtkCommonTransforms
    vtkFiltersGeneral
```
You should be able to `make rtlib` on its own to test this. If, after that, any of the apps fail to build, they likely are adding link dependencies not required by `rtlib`.

2019-04-16 17:22 UTC, stephenrparsons commented
Ready for review

2019-04-16 17:51 UTC, csparker247 requested changes
@stephenrparsons Can you test this in your Singularity container? I just changed some linkage for the other deps and I want to make sure it's still compatible.

2019-04-17 13:17 UTC, csparker247 approved these changes

2019-05-03 13:13 UTC, csparker247 approved these changes

2019-05-03 13:13 UTC, merged